name: fake-news-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - jupyter
  - jupyterlab
  - ipykernel
  - notebook
  - matplotlib
  - matplotlib-inline
  - seaborn
  - beautifulsoup4
  - requests
  - pip
  - pyyaml
  - git-lfs
  - gensim
  - nltk
  - pip:
    - sent2vec
